[ui]
agent_panel_sort = "priority"

[keys]
prefix = "ctrl+space"
detach = "prefix+d"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
previous_tab = ["prefix+p", "ctrl+alt+["]
next_tab = ["prefix+n", "ctrl+alt+]"]
new_tab = ["prefix+c", "ctrl+alt+c"]
rename_tab = ["prefix+,"]
split_vertical = ["prefix+\\"]
split_horizontal = ["prefix+-"]
focus_pane_left = ["alt+h"]
focus_pane_right = ["alt+l"]
focus_pane_up = ["alt+k"]
focus_pane_down = ["alt+j"]


# navigate_pane_left
# navigate_pane_down
# navigate_pane_up
# navigate_pane_right
