#!/usr/bin/env bash

# Script for refreshing AWS isengard credentials using ada.
# Credentials are stored in an AWS profile.
#
# toolbox install ada
#
# Usage: aws-refresh-creds [NAME] [--once]
#   [NAME] is one of: desktop-gamma | chat-gamma | chat-prod
#   default is personal, for my personal account

set -eu

SCRIPT_NAME=$(basename "$0")

PERSONAL_AWS_ACCOUNT=730335495947
PERSONAL_ROLE=admin

DESKTOP_GAMMA_AWS_ACCOUNT=230592382359
# DESKTOP_GAMMA_ROLE=admin
DESKTOP_GAMMA_ROLE=ReadOnly

CHAT_GAMMA_AWS_ACCOUNT=265613951504
CHAT_GAMMA_ROLE=admin

CHAT_PROD_AWS_ACCOUNT=194704208190
CHAT_PROD_ROLE=admin

FIG_TOOLBOX_AWS_ACCOUNT=211125606403
FIG_TOOLBOX_ROLE=admin

METRICS_AWS_ACCOUNT=421629052180
METRICS_ROLE=ReadOnly

RTS_AWS_ACCOUNT=678005972646
RTS_ROLE=ReadOnly

function log {
    echo "$SCRIPT_NAME: $*"
}

function help {
    echo "USAGE: $SCRIPT_NAME [gamma]"
    exit 1
}


# Defaults
PROFILE=personal
AWS_ACCOUNT="$PERSONAL_AWS_ACCOUNT"
ROLE="$PERSONAL_ROLE"

ARG=''
ONCE_FLAG=''

# Set override
while [ "$#" -gt 0 ]; do
    case "$1" in
        --once)
            ONCE_FLAG="--once"
            shift
            ;;
        *)
            ARG="$1"
            shift
            ;;
    esac
done

if [ "${ARG:-}" = "desktop-gamma" ]; then
    AWS_ACCOUNT="$DESKTOP_GAMMA_AWS_ACCOUNT"
    ROLE="$DESKTOP_GAMMA_ROLE"
    PROFILE=desktop-gamma
fi
if [ "${ARG:-}" = "chat-gamma" ]; then
    AWS_ACCOUNT="$CHAT_GAMMA_AWS_ACCOUNT"
    ROLE="$CHAT_GAMMA_ROLE"
    PROFILE=chat-gamma
fi
if [ "${ARG:-}" = "chat-prod" ]; then
    AWS_ACCOUNT="$CHAT_PROD_AWS_ACCOUNT"
    ROLE="$CHAT_PROD_ROLE"
    PROFILE=chat-prod
fi
if [ "${ARG:-}" = "toolbox" ]; then
    AWS_ACCOUNT="$FIG_TOOLBOX_AWS_ACCOUNT"
    ROLE="$FIG_TOOLBOX_ROLE"
    PROFILE=toolbox
fi
if [ "${ARG:-}" = "metrics" ]; then
    AWS_ACCOUNT="$METRICS_AWS_ACCOUNT"
    ROLE="$METRICS_ROLE"
    PROFILE=metrics
fi
if [ "${ARG:-}" = "rts" ]; then
    AWS_ACCOUNT="$RTS_AWS_ACCOUNT"
    ROLE="$RTS_ROLE"
    PROFILE=rts
fi

# Log which account is being used
if [ "$AWS_ACCOUNT" -eq "$DESKTOP_GAMMA_AWS_ACCOUNT" ]; then
    log "Refreshing Desktop Gamma account"
elif [ "$AWS_ACCOUNT" -eq "$CHAT_GAMMA_AWS_ACCOUNT" ]; then
    log "Refreshing Chat Gamma account"
elif [ "$AWS_ACCOUNT" -eq "$CHAT_PROD_AWS_ACCOUNT" ]; then
    log "Refreshing Chat Prod account"
elif [ "$AWS_ACCOUNT" -eq "$FIG_TOOLBOX_AWS_ACCOUNT" ]; then
    log "Refreshing Fig Toolbox Vendor account"
elif [ "$AWS_ACCOUNT" -eq "$PERSONAL_AWS_ACCOUNT" ]; then
    log "Refreshing Personal account"
elif [ "$AWS_ACCOUNT" -eq "$METRICS_AWS_ACCOUNT" ]; then
    log "Refreshing Metrics account"
elif [ "$AWS_ACCOUNT" -eq "$RTS_AWS_ACCOUNT" ]; then
    log "Refreshing RTS account"
else
    help
fi

log "Refreshing credentials for account ${AWS_ACCOUNT} with role ${ROLE}"

ada credentials update --account="${AWS_ACCOUNT}" --provider=isengard --role="${ROLE}" --profile "$PROFILE" "$ONCE_FLAG"

