#!/usr/bin/env sh

cnf add "$HOME/.bin"
cnf add "$HOME/.commonrc"
cnf add "$HOME/.common_aliases"
cnf add "$HOME/.config/nvim/"
cnf add "$HOME/.config/nvim_0_12/"
cnf add "$HOME/.config/kitty/"
cnf add "$HOME/.config/alacritty/"
cnf add "$HOME/.config/wezterm/"

cnf add "$HOME/.config/fish/conf.d/common.fish"

# cnf add "$HOME/.config/Code/User/settings.json"
# cnf add "$HOME/.config/Code/User/keybindings.json"

cnf add "$HOME/.tmux.conf"
cnf add "$HOME/.tmux/sessions/"
cnf add "$HOME/.tmux/config/"
cnf add "$HOME/.gitconfig"
cnf add "$HOME/.gitignore"
cnf add "$HOME/README.md"
echo "Added"

