#!/usr/bin/env sh

rm -f .cli-rust-log.txt .cli-tui-log.txt
KIRO_CHAT_LOG_FILE=.cli-rust-log.txt \
KIRO_TUI_LOG_FILE=.cli-tui-log.txt \
KIRO_TUI_LOG_LEVEL=debug \
KIRO_LOG_NO_COLOR=1 \
KIRO_LOG_LEVEL=chat_cli=trace,chat_cli_v2=trace,agent=trace \
    ~/workplace/kiro-cli-chat-dev/build/kiro-cli-chat "$@"
    # kiro-cli "$@"

