#!/usr/bin/env sh

cleanup() {
    [ -n "$TEMP_FILE" ] && rm -f "$TEMP_FILE"
}

trap cleanup EXIT INT TERM

TEMP_FILE=$(mktemp)
mwcurl https://paste.amazon.com/show/bontalaa/1762201476.text > "$TEMP_FILE"
python3 "$TEMP_FILE"
