#!/usr/bin/env sh

export CLAUDE_CODE_USE_BEDROCK=1
# export ANTHROPIC_MODEL='anthropic.claude-sonnet-4-20250514-v1:0'
# export ANTHROPIC_MODEL='arn:aws:bedrock:us-west-2:730335495947:inference-profile/us.anthropic.claude-sonnet-4-20250514-v1:0'
# export ANTHROPIC_MODEL='anthropic.claude-3-7-sonnet-20250219-v1:0'
export ANTHROPIC_MODEL='arn:aws:bedrock:us-west-2:730335495947:inference-profile/us.anthropic.claude-3-7-sonnet-20250219-v1:0'
export AWS_REGION=us-west-2
export AWS_PROFILE=personal

claude

