require("kiser/defaults")
require("kiser/keymaps")
require("kiser/plugins")
require("kiser/colorscheme")
require("kiser/cmp")
require("kiser/lsp")
require("kiser/dap")
require("kiser/treesitter")
require("kiser/comment")
require("kiser/autopairs")
require("kiser/telescope")
require("kiser/nvim-tree")
require("kiser/gitsigns")
require("kiser/bufferline")
require("kiser/lualine")
require("kiser/which-key")

